### ISSUE TITLE
Does it support Server Side rendering ?

### ISSUE THREAD

**Issue by pravinarr** [darenju/react-flip-page#61]
Hello,

I am creating a SSR react application with express server. I tried to include flip page animation but ended up getting the following error t.defineProperty(o,"defa

ReferenceError: window is not defined
    at Object.<anonymous> (/Users//git///node_modules/react-flip-page/dist/index.js:1:316)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users//git///dist/server.js:238:18)
    at __webpack_require__ (/Users//git///dist/server.js:20:30)

Does this package support SSR ? if yes, is there a way to fix this issue ?

thank you in advance.

**Comment by kkomelin** [comment]
This may give an idea for those who are still in search https://github.com/zeit/next.js/wiki/FAQ
Briefly:
1) You may want to use dynamic imports of Next.js https://github.com/zeit/next.js/pull/1750
2) Or this project for custom SSR server https://github.com/kadirahq/react-no-ssr

**Comment by Ashar2shahid** [comment]
For those still struggling 
```
import dynamic from "next/dynamic";  
const FlipPage = dynamic(() => import("react-flip-page"), {
  ssr: false,
});


function yourComponent() {
return(
 <FlipPage>
 <div>1</div>
 <div>2</div>
 </FlipPage>
 )
}
```
